version: 1

disable_existing_logging: False

formatters:
  default:
    format: '%(asctime)s -- %(levelname)s -- [%(module)s]: %(message)s'
    datefmt: "%Y-%m-%d @ %H:%M:%S.%s"

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - default
    propagate: no

  app:
    level: DEBUG
    handlers:
      - default
    propagate: no

root:
  level: WARNING
  handlers: 
    - default
  propagate: no
